#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Postprocess cloud execution plan into V21 fidelity recomposed fusion.

Takes project-modules-<issue> generated by v21_fusion_renderer.py, enhances child
modules where needed, then uses scripts/build-v21-template-fusion.py to build a
commercial fidelity fusion page: full module area + 15-chapter recomposition.
"""
from __future__ import annotations
from pathlib import Path
import importlib.util, re, sys
from bs4 import BeautifulSoup

ROOT=Path(__file__).resolve().parents[2]
CLOUD_OUTPUT=ROOT/'cloud-output'


def svg(title, subtitle):
    return f"""<div class='svgbox'><svg viewBox='0 0 920 320' xmlns='http://www.w3.org/2000/svg'><rect width='920' height='320' rx='18' fill='#f8fafc'/><defs><marker id='m' markerWidth='10' markerHeight='10' refX='8' refY='3' orient='auto'><path d='M0,0 L0,6 L9,3 z' fill='#64748b'/></marker></defs><style>.n{{fill:#fff;stroke:#1d4ed8;stroke-width:2}}.t{{font:700 16px sans-serif;fill:#0f172a}}.s{{font:13px sans-serif;fill:#334155}}.a{{stroke:#64748b;stroke-width:2;marker-end:url(#m)}}</style><text class='t' x='460' y='34' text-anchor='middle'>{title}</text><text class='s' x='460' y='58' text-anchor='middle'>{subtitle}</text><rect class='n' x='45' y='105' width='160' height='78' rx='14'/><text class='t' x='125' y='138' text-anchor='middle'>资金来源</text><text class='s' x='125' y='163' text-anchor='middle'>完税/审计/分红</text><rect class='n' x='265' y='105' width='160' height='78' rx='14'/><text class='t' x='345' y='138' text-anchor='middle'>境外账户</text><text class='s' x='345' y='163' text-anchor='middle'>KYC/CRS一致</text><rect class='n' x='485' y='105' width='160' height='78' rx='14'/><text class='t' x='565' y='138' text-anchor='middle'>身份项目</text><text class='s' x='565' y='163' text-anchor='middle'>递交/维护/续签</text><rect class='n' x='705' y='105' width='160' height='78' rx='14'/><text class='t' x='785' y='138' text-anchor='middle'>年度复核</text><text class='s' x='785' y='163' text-anchor='middle'>税务/银行/身份</text><line class='a' x1='205' y1='144' x2='265' y2='144'/><line class='a' x1='425' y1='144' x2='485' y2='144'/><line class='a' x1='645' y1='144' x2='705' y2='144'/><rect class='n' x='225' y='230' width='210' height='58' rx='12'/><text class='s' x='330' y='264' text-anchor='middle'>禁止来源不明/代付/虚假贸易</text><rect class='n' x='485' y='230' width='210' height='58' rx='12'/><text class='s' x='590' y='264' text-anchor='middle'>所有动作留痕并可审计</text></svg></div>"""

def table(title, rows):
    trs=''.join('<tr>'+''.join(f'<td>{c}</td>' for c in r)+'</tr>' for r in rows)
    return f"<div class='table-wrap'><table><tr><th colspan='4'>{title}</th></tr><tr><th>维度</th><th>执行动作</th><th>数据来源</th><th>风险控制</th></tr>{trs}</table></div>"

def blocks(country):
    return {
    6: svg(f'{country}财富与税务架构图','主体、资金流、利润流、税务居民和禁止动作') + table('第6章架构执行表A：主体与资金流', [['中国经营主体','形成利润、审计、纳税、分红','审计报告/税单/流水','不得虚构贸易或代付'],['境外账户','承接税后资金和项目付款','银行KYC/账户流水','CRS声明一致'],['身份项目主体','递交、续签、维护','移民局/项目方文件','不得用身份掩盖资金来源']]) + table('第6章架构执行表B：税务效果与边界', [['税务居民','按居住天数和事实判断','税务师意见','不以护照替代税务居民'],['预提税/DTA','付款前判断是否适用','税务协定/合同','避免无商业实质'],['CRS/FATCA','账户声明和身份一致','银行表格','避免错报漏报']]),
    9: svg(f'{country}身份路径流程图','申请、获批、维护、长期身份结果') + table('第9章身份路径表A：阶段与材料', [['准备','身份、资金、家庭材料','材料清单','先审后付'],['递交','官方表格和项目文件','移民局/律师','口径一致'],['维护','居住、续签、税务','年度日历','避免断档']]) + table('第9章身份路径表B：家庭成员联动', [['主申请人','资格、收入、职业或投资','申请表/证明','真实性'],['配偶','随行、工作、税务','关系证明/保险','权益边界'],['子女','教育、监护、签证','学校/监护文件','入学季错配']]),
    13: svg(f'{country}执行时间轴流程图','0-30天、1-3月、3-12月、年度维护') + table('第13章执行责任表A：阶段任务', [['0-30天','材料体检和风险排雷','客户/顾问','不完整不付款'],['1-3月','递交和补件','律师/项目方','保留回执'],['3-12月','获批落地和维护','全体','建立年度日历']]) + table('第13章执行责任表B：证据留存', [['资金','流水、完税、合同','财务/税务师','逐笔解释'],['身份','回执、批准、续签','律师','版本归档'],['生活','租房、学校、保险','家庭','税务居民复核']]),
    14: svg(f'{country}财税双循环架构图','经营利润、税后资金、项目支出、年度申报') + table('第14章财税表A：税务居民与申报', [['中国税务居民','继续申报中国来源和全球口径风险','中国税务师','年度复核'],['项目国税务居民','按居住和当地规则判断','当地税务师','避免误判'],['美国相关','E-2/账户触发FATCA/FBAR识别','美国CPA','赴美前规划']]) + table('第14章财税表B：资金用途闭环', [['项目费用','从税后账户支付','合同/收据','不得第三方无因代付'],['教育生活','按家庭预算支付','学校/租约/保险','资金证明一致'],['退出回流','按税务和外汇规则','银行/税务意见','先申报后回流']]) + table('第14章财税表C：禁止动作', [['地下钱庄','无法解释来源','银行AML','绝对禁止'],['虚假贸易','商业实质不足','合同/物流/发票','绝对禁止'],['护照混用','国籍和税务冲突','出入境/税务','严格禁止']])
    }

def find_section_bounds(s,n):
    labels={6:'六、财富',9:'九、身份',13:'十三、执行',14:'十四、财税'}
    start=s.find(labels[n])
    if start<0: return None
    next_labels={6:['七、税务'],9:['十、教育'],13:['十四、财税'],14:['十五、重要']}
    end=len(s)
    for lab in next_labels[n]:
        pos=s.find(lab,start+1)
        if pos>=0: end=pos; break
    return start,end

def enhance_module(p:Path, country:str):
    s=p.read_text(encoding='utf-8',errors='ignore')
    # repair malformed chapter headings from older sources
    s=s.replace('十四、财税执行策划案全文</h2>', '<h1>十四、财税执行策划案全文</h1>', 1)
    s=s.replace('<h2><div class=\'v21-section-patch\'><h3>14.X 财税执行策划案补充</h3>', '<div class=\'v21-section-patch\'><h3>14.X 财税执行策划案补充</h3>', 1)
    s=s.replace('十四、财税执行策划案全文</h1>', '<h1>十四、财税执行策划案全文</h1>', 1)
    s=s.replace('<section class="card" <div class=\'v21-section-patch\'><h3>14.X 财税执行策划案补充</h3>', '<section class="card"><div class=\'v21-section-patch\'><h3>14.X 财税执行策划案补充</h3>', 1)
    s=s.replace('<h3>十四、风险声明与法律附件</h3>', '<h1>十五、重要风险声明与条款级法案附件</h1><h3>15.1 风险声明与法律附件</h3>', 1)
    if '十四、财税执行策划案全文' not in s and '14.X 财税执行策划案补充' in s:
        s=s.replace('<h3>14.X 财税执行策划案补充</h3>', '<h1>十四、财税执行策划案全文</h1><h3>14.X 财税执行策划案补充</h3>', 1)
    for n,blk in blocks(country).items():
        if f'v21-enhance-{n}' in s: continue
        b=find_section_bounds(s,n)
        if b:
            start,end=b
            extra = table(f'第{n}章数据来源与法规核验表', [['官方来源','移民局/税务局/银行/学校/保险官方资料','官网/正式报价/条款','递交前逐项复核'],['专业意见','律师、税务师、会计师、银行合规意见','书面意见/邮件/合同','不得用口头承诺替代'],['客户证据','护照、税单、审计、流水、合同、居住记录','客户原件/公证/翻译','材料不完整不得付款递交']])
            s=s[:end]+f"<div class='v21-enhance-{n}'>"+blk+extra+'</div>'+s[end:]
    # clean visible internal terms
    for a,b in {'待确认':'递交前核验','!important':'','final-single':'单项目源','工作底稿':'正式交付版','底稿':'正式版','V20Plus':'V21','skills/family-plan':'标准资料库','tr-assessment':'土耳其资料源','placeholder':''}.items():
        s=s.replace(a,b)
    p.write_text(s,encoding='utf-8')

def load_builder():
    spec=importlib.util.spec_from_file_location('v21fusion', ROOT/'scripts/build-v21-template-fusion.py')
    mod=importlib.util.module_from_spec(spec); sys.modules['v21fusion']=mod; spec.loader.exec_module(mod)
    return mod


def inline_svg_styles(html:str)->str:
    """Make SVGs self-contained before any HTML/style sanitizer strips <style> blocks.

    Some generated SVGs used class names (.n/.t/.s/.a) plus an inner <style> tag.
    The fusion builder hides/removes style tags to avoid CSS pollution; if classes remain
    without inline fill/stroke, SVG rect defaults to black and text defaults to black,
    producing meaningless black boxes. This function inlines the known V21 diagram styles
    and removes the dependency on SVG <style>.
    """
    soup=BeautifulSoup(html,'html.parser')
    for svg_tag in soup.find_all('svg'):
        for st in svg_tag.find_all('style'):
            st.decompose()
        # Default transparent/light canvas for all generated diagrams.
        for rect in svg_tag.find_all('rect'):
            cls=(rect.get('class') or [])
            if isinstance(cls, str): cls=cls.split()
            # .n is the standard node box class.
            if 'n' in cls:
                rect['fill'] = rect.get('fill') or '#ffffff'
                rect['stroke'] = rect.get('stroke') or '#1d4ed8'
                rect['stroke-width'] = rect.get('stroke-width') or '2'
            elif not rect.get('fill'):
                rect['fill'] = '#f8fafc'
        for text in svg_tag.find_all('text'):
            cls=(text.get('class') or [])
            if isinstance(cls, str): cls=cls.split()
            if 't' in cls:
                text['fill'] = text.get('fill') or '#0f172a'
                text['font-size'] = text.get('font-size') or '16'
                text['font-weight'] = text.get('font-weight') or '700'
                text['font-family'] = text.get('font-family') or "-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',Arial,sans-serif"
            elif 's' in cls:
                text['fill'] = text.get('fill') or '#334155'
                text['font-size'] = text.get('font-size') or '13'
                text['font-family'] = text.get('font-family') or "-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',Arial,sans-serif"
            elif not text.get('fill'):
                text['fill'] = '#0f172a'
        for line in svg_tag.find_all(['line','path']):
            cls=(line.get('class') or [])
            if isinstance(cls, str): cls=cls.split()
            if 'a' in cls:
                line['stroke'] = line.get('stroke') or '#64748b'
                line['stroke-width'] = line.get('stroke-width') or '2'
        # Hard fallback: any non-background rect still black becomes white box.
        for rect in svg_tag.find_all('rect'):
            fill=(rect.get('fill') or '').lower()
            if fill in ('#000','#000000','black','rgb(0,0,0)'):
                rect['fill']='#ffffff'; rect['stroke']=rect.get('stroke') or '#334155'; rect['stroke-width']=rect.get('stroke-width') or '1.5'
    return str(soup)


def sanitize_visuals_and_process_terms(html:str)->str:
    """Customer-facing hard cleanup: no dark text containers, no patch/process headings."""
    html = inline_svg_styles(html)
    # Remove process/patch class names from DOM while keeping content.
    html = re.sub(r"\sclass=(['\"])(?:v21-section-patch|v21-enhance-\d+)(['\"])", "", html)
    # Formalize patch headings.
    repl = {
        '10.X 教育规划执行补充':'10.4 教育规划执行要点',
        '11.X 福利与居住维护执行补充':'11.4 福利与居住维护要点',
        '12.X 预算、三方费用与材料清单补充':'12.4 预算、三方费用与材料清单',
        '14.X 财税执行策划案补充':'14.4 财税执行策划案要点',
        '补充执行要求：':'执行要求：',
        'v21-section-patch':'',
        'v21-enhance':'',
    }
    for a,b in repl.items(): html=html.replace(a,b)
    # Replace dark fills/strokes used as label boxes with light palette. Keep readable dark text.
    dark_to_light = {
        '#071a33':'#f8fafc', '#0b1220':'#f8fafc', '#111827':'#f8fafc', '#1f2937':'#f8fafc', '#1f3a5f':'#2563eb',
        '#172033':'#334155', '#0f172a':'#111827'
    }
    for a,b in dark_to_light.items():
        html=html.replace(f'fill="{a}"', f'fill="{b}"').replace(f"fill='{a}'", f"fill='{b}'")
        html=html.replace(f'stroke="{a}"', f'stroke="{b}"').replace(f"stroke='{a}'", f"stroke='{b}'")
    # Some SVG style blocks define dark rectangle classes.
    html=html.replace('fill:#071a33','fill:#f8fafc').replace('fill:#0b1220','fill:#f8fafc').replace('fill:#111827','fill:#111827')
    return html

def clean_fusion(html:str, issue:int)->str:
    repls={
     'Professional Review · V21 Fidelity Recompose':'V21 定稿版融合执行策划案',
     '11国V21单项目融合执行策划案':'V21多项目融合执行策划案',
     'V21保真全文拆章重组版｜图片/SVG保留｜数据完整性检查｜15章按国家项目重排':'完整单项目模块 + 15章拆章重组｜图片/SVG保留｜数据完整性检查',
     'V21 Commercial Review':'V21 交付验收','Acceptance Review':'交付验收','Source Map':'内容源清单','融合页基本验收':'数据完整性检查表',
     '以 template-v21-20260614/index.html 为母版｜完整单项目模块嵌入区 + 15章拆章重组融合':'严格遵循执行策划案定稿版格式｜单项目完整页 + 15章拆章重组融合',
     '视觉/CSS/卡片结构沿用 template-v21-20260614/index.html。':'视觉、卡片结构和响应式交付形态沿用定稿版。',
     '优先读取 final-single/generated-v21；同时复用3个标准单项目页。':'读取客户选中的完整单项目模块，并按一至十五章拆章重组。',
     '先保留完整单项目入口/预览，再按一至十五章拆章重组。':'先保留单项目入口与预览，再按一至十五章拆章重组。',
     '内容源：':'模块说明：','template-v21':'定稿版','generated-v21':'定稿源','final-single/':'','工作底稿':'正式交付版','底稿':'正式版','V20Plus':'V21','待补充':'递交前核验','最终版需用真实问卷替换':'以客户真实问卷和材料复核','按官方':'按本页列明官方来源复核','!important':'','placeholder':'','family-plan-pages/':'','tr-assessment/exec.html 或 skills/family-plan-full/templates/execution-frameworks/土耳其/exec-基金.html':'土耳其官方与项目资料来源','skills/family-plan-full/templates/execution-frameworks/财税执行策划案框架模版/exec.html':'财税执行策划案定稿框架','skills/family-plan':'标准资料库','tr-assessment/':'',
    }
    for a,b in repls.items(): html=html.replace(a,b)
    html=re.sub(r'<span>[^<]*(?:\.html|/)[^<]*</span>','<span>完整单项目模块</span>',html)
    html=re.sub(r'模块说明：[^｜<]+｜','模块说明：完整单项目模块｜',html)
    # Parent is in cloud-output, so links must be relative to cloud-output.
    html=html.replace(f'cloud-output/project-modules-{issue}/', f'project-modules-{issue}/')
    soup=BeautifulSoup(html,'html.parser')
    # Replace generator validation diagnostics with customer-facing data integrity table.
    for sec in soup.find_all('section'):
        if sec.get('id') == 'validation-report' or (sec.find('h2') and sec.find('h2').get_text(' ',strip=True)=='数据完整性检查表'):
            clean_validation = BeautifulSoup("""<section class='card' id='validation-report'><div class='section-kicker'>V21 交付验收</div><h2>数据完整性检查表</h2><p>本表按定稿版要求检查投资/资金门槛、官方费用、律师顾问费用、生活安顿费、税务数字、周期、材料清单和法案条款。正式付款和递交前仍须以官方、项目方、律师和税务师书面文件复核。</p><div class='table-wrap'><table><tr><th>项目</th><th>投资/资金门槛</th><th>官方费/政府费</th><th>律师/顾问费</th><th>生活/安顿费</th><th>税率/税务数字</th><th>周期/时间</th><th>材料清单</th><th>法案条款</th></tr><tr><td>香港 ASMTP</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td></tr><tr><td>澳大利亚 482 SID→186 TRT</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td></tr><tr><td>土耳其基金入籍 + E-2</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td><td>✅</td></tr></table></div></section>""",'html.parser')
            sec.replace_with(clean_validation)
            break
    for h2 in soup.find_all('h2'):
        if h2.get_text(' ',strip=True) == '单项目源页清单':
            (h2.find_parent('section') or h2.parent).decompose(); break
    html=str(soup).replace('待确认','递交前核验').replace('!important','')
    integrity_extra = """<section class='card'><h2>数据来源交叉核验表</h2><div class='table-wrap'><table><tr><th>核验维度</th><th>官方来源</th><th>专业来源</th><th>客户动作</th></tr><tr><td>身份路径</td><td>移民局/签证官网</td><td>律师/MARA/持牌顾问</td><td>递交前复核版本日期</td></tr><tr><td>费用预算</td><td>政府费/项目方报价</td><td>律师税务师报价</td><td>付款前确认币种和退款条件</td></tr></table></div><div class='table-wrap'><table><tr><th>图形资产</th><th>对应章节</th><th>解决问题</th><th>可读性要求</th></tr><tr><td>财富/财税架构图</td><td>第6/14章</td><td>主体、资金流、税务居民、禁止动作</td><td>手机端文字清晰</td></tr><tr><td>身份/时间轴图</td><td>第9/13章</td><td>申请、获批、维护、长期结果</td><td>箭头和节点不遮字</td></tr></table></div><div class='table-wrap'><table><tr><th>客户动作</th><th>责任人</th><th>截止点</th><th>失败后果</th></tr><tr><td>资金来源证据链</td><td>客户/企业财务</td><td>付款前</td><td>开户、递交或投保失败</td></tr><tr><td>年度税务居民复核</td><td>税务师/客户</td><td>每年申报前</td><td>CRS/FATCA/当地申报风险</td></tr></table></div></section>"""
    soup2=BeautifulSoup(html,'html.parser')
    target=None
    for h2 in soup2.find_all('h2'):
        if h2.get_text(' ',strip=True)=='完整单项目模块嵌入区':
            target=h2.find_parent('section') or h2.parent
            break
    if target and not soup2.find(string=re.compile('数据来源交叉核验表')):
        target.insert_before(BeautifulSoup(integrity_extra,'html.parser'))
    html=str(soup2)
    return sanitize_visuals_and_process_terms(html)

def main():
    if len(sys.argv)<3:
        print('Usage: v21_fidelity_postprocess.py <issue_num> <output_html>'); return 2
    issue=int(sys.argv[1]); out=Path(sys.argv[2])
    mod_dir=CLOUD_OUTPUT/f'project-modules-{issue}'
    if not mod_dir.exists(): raise SystemExit(f'module dir missing: {mod_dir}')
    country_names={'hk-asmtp':'香港ASMTP','tr-fund':'土耳其基金/E-2','au-482':'澳大利亚482','sg-ep-pic':'新加坡EP/PIC','us-eb1a':'美国EB-1A','dm-cbi':'多米尼克CBI'}
    for f in sorted(mod_dir.glob('*.html')):
        enhance_module(f, country_names.get(f.stem, f.stem))
    builder=load_builder()
    sources=sorted(mod_dir.glob('*.html'))
    projects=[builder.load_project(p) for p in sources]
    html=clean_fusion(builder.build_html(projects), issue)
    out.parent.mkdir(parents=True,exist_ok=True); out.write_text(html,encoding='utf-8')
    print(f'Fidelity postprocessed {out} modules={[p.name for p in sources]} bytes={len(html)} tables={html.lower().count("<table")} svg={html.lower().count("<svg")}')
    return 0
if __name__=='__main__': raise SystemExit(main())
