name = "family-plan-issue-proxy"
main = "src/index.js"
compatibility_date = "2026-06-18"
account_id = "2c56642c45c5b9c31dff837c0c513290"
workers_dev = true

[vars]
GITHUB_REPO = "sewen38/family-plan"
ALLOWED_ORIGIN = "https://sewen38.github.io"
